# Generated by Django 3.0.4 on 2020-03-24 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=8, verbose_name='Número do pedido')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultima Atualização')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('unfulfilled', 'Unfulfilled'), ('partially fulfilled', 'Partially fulfilled'), ('fulfilled', 'Fulfilled'), ('canceled', 'Canceled')], max_length=32)),
                ('token', models.CharField(blank=True, max_length=36, unique=True)),
                ('checkout_token', models.CharField(blank=True, max_length=36)),
                ('customer_note', models.TextField(blank=True, default='')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_cliente', to='customer.Customer')),
                ('ship_address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='customer.Address')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-number'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=386)),
                ('item_sku', models.CharField(max_length=32)),
                ('qt', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Quantidade')),
                ('gross_price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Valor Original')),
                ('net_price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Valor liquido')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_item', to='item.Item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_pedido', to='order.Order')),
            ],
            options={
                'verbose_name': 'Itens de pedido',
                'verbose_name_plural': 'Itens de pedidos',
            },
        ),
    ]
