# Generated by Django 3.0.4 on 2020-03-24 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Produto')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('bar_code', models.CharField(max_length=13, verbose_name='Código de barras')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Preço')),
            ],
            options={
                'verbose_name': 'Item de estoque',
                'verbose_name_plural': 'Itens de estoque',
            },
        ),
    ]
